### PR TITLE
simplify aws install and add install for dev scripts

### PR DESCRIPTION
**Pull request by paololim**

### CODE REVIEW

**Comment by paololim** [comment]
@benwaffle @pnguyen if you guys know a better to do this, let me know. otherwise, the image this produces works for me.

**Comment by benwaffle** [comment]
`go get` should download dependencies for you. i'm giving it a stab...

**Comment by paololim** [comment]
@benwaffle note reason for the workaround is that `go get` doesn't work out of the box for private repos (`flowcommerce/tools` is private)

**Comment by benwaffle** [comment]
Can't we just copy the `dev` binary from the host into the container?

**Comment by paololim** [comment]
Didn't occur to me to try. Is the binary built on mac os compatible in ubuntu?

**Comment by benwaffle** [comment]
ah nope, forgot about that

**Comment by benwaffle** [comment]
can we build linux binaries on macos

**Pull request merged**
