### PR TITLE
[CHEC-899] Node: Update Java, Simplify container config

### PR DESCRIPTION
**Pull request by RoryH**
With a view to updating the Node docker images, making sure our build script run. The version of Java we specify caused a conflict with the one expected by the node-alpine image, upgrading to allow building.

Current images can not build, I tested with this change and images build ok after the change.

### CODE REVIEW

**Comment by benwaffle** [comment]
If you don't care which java version is running, just install openjdk11-jre, and use it with `java`

**Comment by RoryH** [comment]
@benwaffle, done, tested locally and images build ok

**Comment by benwaffle** [comment]
The only reason you need java is for environment-provider.jar right? Is it needed in the builder image?

**Comment by benwaffle** [comment]
Will something like this still work?

```diff
diff --git a/node/Dockerfile.node b/node/Dockerfile.node
index 9ee75af..115bd58 100644
--- a/node/Dockerfile.node
+++ b/node/Dockerfile.node
@@ -5,23 +5,9 @@ LABEL maintainer="tech@flow.io"
 # Default to UTF-8 file.encoding
 ENV LANG C.UTF-8
 
-ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk
-ENV JAVA_ALPINE_VERSION 11.0.4_p4-r1
 ENV NODE_ENV production
-ENV PATH $PATH:/usr/lib/jvm/java-11-openjdk/jre/bin:/usr/lib/jvm/java-11-openjdk/bin
-
-# add a simple script that can auto-detect the appropriate JAVA_HOME value
-# based on whether the JDK or only the JRE is installed
-RUN { \
-		echo '#!/bin/sh'; \
-		echo 'set -e'; \
-		echo; \
-		echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
-	} > /usr/local/bin/docker-java-home && \
-	chmod +x /usr/local/bin/docker-java-home && \
-  set -x && \
-	apk add --no-cache openjdk11-jre="$JAVA_ALPINE_VERSION" && \
-	[ "$JAVA_HOME" = "$(docker-java-home)" ]
+
+RUN	apk add --no-cache openjdk11-jre
 
 WORKDIR /root
 
diff --git a/node/Dockerfile.node_builder b/node/Dockerfile.node_builder
index 99c19aa..8fe7979 100644
--- a/node/Dockerfile.node_builder
+++ b/node/Dockerfile.node_builder
@@ -5,33 +5,15 @@ LABEL maintainer="tech@flow.io"
 # Default to UTF-8 file.encoding
 ENV LANG C.UTF-8
 
-ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk
-ENV JAVA_ALPINE_VERSION 11.0.4_p4-r1
 ENV NODE_ENV production
 ENV GOPATH /root/go
 ENV GOBIN $GOPATH/bin
-ENV PATH $PATH:/usr/lib/jvm/java-11-openjdk/jre/bin:/usr/lib/jvm/java-11-openjdk/bin:$GOBIN
+ENV PATH $PATH:$GOBIN
 
 ARG GITHUB_TOKEN
 
-# add a simple script that can auto-detect the appropriate JAVA_HOME value
-# based on whether the JDK or only the JRE is installed
-RUN { \
-		echo '#!/bin/sh'; \
-		echo 'set -e'; \
-		echo; \
-		echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
-	} > /usr/local/bin/docker-java-home && \
-	chmod +x /usr/local/bin/docker-java-home && \
-  set -x && \
-	apk add --no-cache --update openjdk11-jre="$JAVA_ALPINE_VERSION" && \
-	[ "$JAVA_HOME" = "$(docker-java-home)" ]
-
 WORKDIR /root
 
-COPY environment-provider.jar .
-COPY environment-provider-version.txt .
-
 RUN npm install -g forever && \
     apk add --no-cache --update python py-pip ca-certificates musl-dev git go dep make build-base && \
     pip install --upgrade awscli && \

```

**Comment by RoryH** [comment]
@benwaffle Implemented that, just not sure of the repercussions of JAVA_HOME possibly not being set appropriately now? I have no knowledge of what that might mean, if you're happy that is ok we should be good to go.

**Comment by RoryH** [comment]
[CHEC-899]

**Review by benwaffle — APPROVED** [review]

**Pull request merged**
