### PR TITLE
Explicitly set DNS TTL to 10 seconds

### PR DESCRIPTION
**Pull request by grahamar**

### CODE REVIEW

**Comment by grahamar** [comment]
Open to suggestions on what we want the TTL to be

**Comment by paololim** [comment]
lgtm

**Comment by paololim** [comment]
@pnguyen @benwaffle wdyt?

**Comment by benwaffle** [comment]
@grahamar if you think it's only a problem on oraclejdk, why apply it to openjdk?

**Comment by grahamar** [comment]
Regardless of oracle or openjdk, if a user sets a security manager in any app the default is forever and if no security manger is set the default is 30 seconds which is arguably too long...

**Pull request merged**
